### ISSUE TITLE
Option to hide read more

### ISSUE THREAD

**Issue by harikesh409** [chrisj74/vue-rss-blog#1]
A data attribute to hide the read more button as we already have the link on the title to redirect to the external link.

**Comment by chrisj74** [comment]
Thanks for the suggestion. You can hide with CSS in your page, there is a  `read-more` class on the link already. Happy to help with the css is you post a link to your page.

**Comment by harikesh409** [comment]
Thanks for the suggestion, wrote the CSS with that class now it is solved.
