### ISSUE TITLE
Unable to Filter Out Comments

### ISSUE THREAD

**Issue by ethanosullivan** [chrisj74/vue-rss-blog#11]
First off, I want to say that this tool is great. I have yet to come across something like this. My website is a static HTML hosted on GitHub after I moved away from WordPress and wanted to focus on better performance and security. I started to get into blogging and use Medium as my platform of choice. Now I can easily embed this widget on my website and continue posting on Medium.

While I was setting it up, I see that my comments show up in the widget. You can check out my Medium feed for reference and replicate the issue:
```
https://medium.com/feed/@ethanosullivan
```

When you look at my feed ([converted to JSON](https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Fmedium.com%2Ffeed%2F%40ethanosullivan)), the only way to determine if it's a comment is when the `categories` field is empty:
```
...
            "categories": []
...
```

For a feature update, it would be nice if there can be an option to hide the comments in the data attributes, like so:
```
<div id="retainable-rss-embed"
         data-rss="https://medium.com/feed/@ethanosullivan"
...
         data-comments="off"></div>
```

**Comment by ethanosullivan** [comment]
Hi @chrisj74 - just following up on my initial comment, have you had a chance to go over it?

**Comment by chrisj74** [comment]
Hi Ethan,

The feed for individuals is different to the feed for publications. If you moved your posts to a publication then the problem goes away, if you leave as a personal feed, many of your slots (medium limits the number) will be wasted by comments. 

Would you be able to move to a publication?

**Comment by ethanosullivan** [comment]
I see. I just created my own [publication](https://medium.com/factmaven) and changed the feed URL. That solved the issue, thanks.
