### ISSUE TITLE
Option to limit the number of posts shown

### ISSUE THREAD

**Issue by draganbabic** [chrisj74/vue-rss-blog#2]
First of all thanks for making this, it's really handy for static websites. 

If I understand correctly there isn't a way to limit the number of posts the script shows, correct? I think this would be a rather useful feature.

**Comment by chrisj74** [comment]
Thanks for the suggestion. Do you mean how many in total, how many from each feed or how many to display at once?

If the display one you can control this through the props. If the total, then as it loops through each feed, you would potentially only see posts from one of n feeds. So really the only way would be to limit per feed. Medium already limits this, but could potentially look at a further restriction.

**Comment by draganbabic** [comment]
The main reson I asked is because I didn't see a parameter which would limit the number of posts returned, i.e. `data-limit="3"` so it only return the three latest feed items. Does something like this already exist?

**Comment by chrisj74** [comment]
Thanks to @ema987 for pr. this is now resolved.
