### ISSUE TITLE
Links not working correctly

### ISSUE THREAD

**Issue by simonrae** [chrisj74/vue-rss-blog#4]
External links fail to load when I set `data-layout="grid"` and `data-poststyle="external"`. Only when I set `data-grid="slider"` the read more link is working correctly. 

Seems to be a common issue with other users posted here https://medium.com/p/41ac0a13231e/responses/show

**Comment by chrisj74** [comment]
Hi Simon,

Found the issue and have fixed. You may need to clear your browser cache if it doesn't work straight away for you.

**Comment by simonrae** [comment]
Thanks Chris. The post image looks to be working now, the post title still appears to be disabled.

**Comment by chrisj74** [comment]
Hi Simon, sorry been a long day! Have updated and looked at your site and all 3 links now work as expected. You may need to do a hard refresh or even clear your browser cache.

**Comment by simonrae** [comment]
Thanks Chris. All working now.
