### ISSUE TITLE
More options to format

### ISSUE THREAD

**Issue by sif** [chrisj74/vue-rss-blog#7]
Hi, I am wondering if it's feasible to change the output of the cards. 
Some examples:
a. show/hide the date
b. change date format itself (for example, mm-dd-yyyy)
c. show/hide the word "author" itself
d. manipulate spacing, for example, when I use 'visibility: hidden;' on the 'readmore' buttons, the space that it previously occupied is still there
e. positioning, like order of title, date, summary, etc.

**Comment by chrisj74** [comment]
Hi @sif, most of this can be done through css. 

In the example you give, you should use `display: none`. This essentially removes the element from the dom so no space is preserved.

Date formatting way be more tricky, this would need a new attribute to pass in your formatting rules. I'll see if I get some time to look at this.
