### ISSUE TITLE
remove image from embedded page

### ISSUE THREAD

**Issue by nalangekrushna** [chrisj74/vue-rss-blog#9]
can you please provide some option in which I can avoid using image.

**Comment by chrisj74** [comment]
Hi

You can hide the images using css in your page.

**Comment by chrisj74** [comment]
The code to remove the image is like this:
```
#rtb a.post-image {
    display: none;
}
```
But you will need to work out what to do with the date, one option would be to add this:
```
#rtb .slider-post .post-date {
    position: relative;
    top: 0;
    left: 0;
}
```

Hope this helps.

**Comment by nalangekrushna** [comment]
Thanks for help.
